url: https://ashimajain2595.github.io
baseurl:

# Site settings
title: Ashima Jain
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

people:
- name: Python
  pic: 90
- name: C/C++
  pic: 80
- name: JAVA
  pic: 60
- name: Objective-C
  pic: 75
- name: R
  pic: 75
- name: Octave
  pic: 85
- name: Tensorflow
  pic: 80
- name: Keras
  pic: 75
- name: Theano
  pic: 60
- name: OpenCV
  pic: 85
- name: OpenGL
  pic: 85
- name: Latex
  pic: 70

# Team names, titles and social links
# people:
# - name: Kay Garland
#   pic: 90
#   position: Lead Designer
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: stack-overflow
#       url: #
#
# - name: Larry Parker
#   pic: 20
#   position: Lead Marketer
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: linkedin
#       url: #
#
# - name: Diana Petersen
#   pic: 30
#   position: Lead Developer
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: google-plus
#       url: #
#
# - name: Diana Petersen
#   pic: 50
#   position: Lead Developer
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: google-plus
#       url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
